checking dependencies are upto date

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -26,72 +26,74 @@ jobs:
       - run: go get -v -d ./...
       # - run: go test -v ./...
 
-      - run:
-          name: Build application container
-          command: |
-            # go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
-            [ ! -e bin ] && mkdir bin;
-            go build --ldflags '-extldflags "-static"' -o bin/invoicer .;
-            # cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
-            docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
-            docker images;  
-            echo "---------------------------";
-            docker ps;
-            echo "---------------------------";
-            # ls -R;
-
-      - run:
-          name: Run application in background
-          command: |
-            docker run --name webapp --net=host -d ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
-          background: true
-      
       # - run:
-      #     name: Fetching ip
+      #     name: Build application container
       #     command: |
-      #       sleep 5;
-      #       echo "###########################";
+      #       # go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
+      #       [ ! -e bin ] && mkdir bin;
+      #       go build --ldflags '-extldflags "-static"' -o bin/invoicer .;
+      #       # cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
+      #       docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
+      #       docker images;  
+      #       echo "---------------------------";
       #       docker ps;
-      #       ifconfig;
-      #       docker inspect --format '{{ .NetworkSettings.IPAddress }}' `docker ps -q`;
-      #       _ip=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' \`docker ps -q\``;
-      #       curl -V;
-      #       echo $_ip;
-      #       echo "*********** LOCAL MACHINE **************";
-      #       netstat -antup;
-      #       echo "************ INSIDE DOCKER ***********";
-      #       docker exec `docker ps -q` netstat -antup;
-      #       echo "*****************************************"
-      #       # ping -c 3 webapp;
-      #       # curl http://webapp:8080/;
-      #       # curl --retry 10 --retry-delay 5 -v http://localhost:8080/
-      #       # # docker exec -it `docker ps -q` ls;
-      #       # ip41=$(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)
-      #       # curl http://$ip41:8080/;
-      #       # echo "++++++++++++++++++++";
-      #       curl http://127.0.0.1:8080/;
-      
-      - run:
-          name: Debugging connectivity to webapp
-          command: |
-            docker pull byrnedo/alpine-curl && docker run --net=host byrnedo/alpine-curl localhost:8080
+      #       echo "---------------------------";
+      #       # ls -R;
 
-      - run:
-          name: ZAP baseline test of application
-          # Only fail on error code 1, which indicates at least one FAIL was found.
-          # error codes 2 & 3 indicate WARN or other, and should not break the run
-          command: |
-            (
-            docker pull owasp/zap2docker-weekly && \
-            docker run --net=host -t owasp/zap2docker-weekly zap-baseline.py \
-                -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
-                -t http://localhost:8080/ || \
-            if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
-            )
+      # - run:
+      #     name: Run application in background
+      #     command: |
+      #       docker run --name webapp --net=host -d ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
+      #     background: true
+      
+      # # - run:
+      # #     name: Fetching ip
+      # #     command: |
+      # #       sleep 5;
+      # #       echo "###########################";
+      # #       docker ps;
+      # #       ifconfig;
+      # #       docker inspect --format '{{ .NetworkSettings.IPAddress }}' `docker ps -q`;
+      # #       _ip=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' \`docker ps -q\``;
+      # #       curl -V;
+      # #       echo $_ip;
+      # #       echo "*********** LOCAL MACHINE **************";
+      # #       netstat -antup;
+      # #       echo "************ INSIDE DOCKER ***********";
+      # #       docker exec `docker ps -q` netstat -antup;
+      # #       echo "*****************************************"
+      # #       # ping -c 3 webapp;
+      # #       # curl http://webapp:8080/;
+      # #       # curl --retry 10 --retry-delay 5 -v http://localhost:8080/
+      # #       # # docker exec -it `docker ps -q` ls;
+      # #       # ip41=$(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)
+      # #       # curl http://$ip41:8080/;
+      # #       # echo "++++++++++++++++++++";
+      # #       curl http://127.0.0.1:8080/;
+
+      # - run:
+      #     name: Debugging connectivity to webapp
+      #     command: |
+      #       docker pull byrnedo/alpine-curl && docker run --net=host byrnedo/alpine-curl localhost:8080
+
+      # - run:
+      #     name: ZAP baseline test of application
+      #     # Only fail on error code 1, which indicates at least one FAIL was found.
+      #     # error codes 2 & 3 indicate WARN or other, and should not break the run
+      #     command: |
+      #       (
+      #       docker pull owasp/zap2docker-weekly && \
+      #       docker run --net=host -t owasp/zap2docker-weekly zap-baseline.py \
+      #           -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
+      #           -t http://localhost:8080/ || \
+      #       if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+      #       )
 
       - run:
           name: Test dependencies are up to date
-          command: 'GOPATH="${GOPATH_HEAD}"; ( cd ${GOPATH_BASE}/${CIRCLE_PROJECT_REPONAME} && govend -u --prune && git diff --quiet )'
+          command: |
+            ls ${GOPATH_BASE}/${CIRCLE_PROJECT_REPONAME}
+            GOPATH="${GOPATH_HEAD}"; ( cd ${GOPATH_BASE}/${CIRCLE_PROJECT_REPONAME} && govend -u --prune && git diff --quiet )
 
       - deploy:
           # Push application container to dockerhub
